<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_strongWere sorry but frontend-web does_5b941f</name>
   <tag></tag>
   <elementGuidId>9ce60fc5-55ef-4f7c-b2f7-f0b108afd74f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>c3959c51-a3f7-455d-8ab4-b6634020f3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;strong>We're sorry but frontend-web doesn't work properly without JavaScript enabled. Please enable it to continue.&lt;/strong>AltaShop0LoginEmailPasswordLogin Belum memiliki akun? Registerid(&quot;input-18&quot;)</value>
      <webElementGuid>543160f9-2761-42f1-a3c5-ce79c18b9bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>c60acbd9-ecf4-4ece-adff-64e08975faed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>f4fabbf5-b285-4d14-a894-66f7e50ad97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = concat(&quot;&lt;strong>We&quot; , &quot;'&quot; , &quot;re sorry but frontend-web doesn&quot; , &quot;'&quot; , &quot;t work properly without JavaScript enabled. Please enable it to continue.&lt;/strong>AltaShop0LoginEmailPasswordLogin Belum memiliki akun? Registerid(&quot;input-18&quot;)&quot;) or . = concat(&quot;&lt;strong>We&quot; , &quot;'&quot; , &quot;re sorry but frontend-web doesn&quot; , &quot;'&quot; , &quot;t work properly without JavaScript enabled. Please enable it to continue.&lt;/strong>AltaShop0LoginEmailPasswordLogin Belum memiliki akun? Registerid(&quot;input-18&quot;)&quot;))]</value>
      <webElementGuid>4c66ae79-3358-4e0f-bcf3-f09168e2a2c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
